-- POST Shop
INSERT INTO shops (id, NAME, CAPACITY) VALUES (default, 'Shop 3', 20);

-- Get Shops
SELECT * FROM SHOPS;

-- POST Collar in Shop
INSERT INTO collars (id, NAME, CREATOR, PRICE, ENTRY_DATE, SHOP_ID) VALUES (DEFAULT, 'Collar X', 'Creator a', 2000, '01-04-2021', 3);
INSERT INTO collars (id, NAME, CREATOR, PRICE, ENTRY_DATE, SHOP_ID) VALUES (DEFAULT, 'Collar Xx', NULL, 2200, '01-04-2021', 3);

-- GET Shop's Collars
SELECT * FROM SHOPS, COLLARS WHERE SHOPS.id = COLLARS.SHOP_ID AND SHOPS.ID = 3;

-- DELETE Shop's Collars
DELETE FROM COLLARS WHERE SHOP_ID = 3;